# Generated by Django 3.2.25 on 2024-06-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='color',
        ),
    ]
